
=head1 How to learn programming

* Learn by doing
* Experiment, fail, retry, succeed
* Difficult words
* Undoing mistakes
* Testing your software
* How to track down bugs


=head1 Simple questionnaire

* Keeping track of data (Variables)
* Input and output
* Repeating stuff (Loops)
* Comparing things (Comparison)
* Deciding what has to be done (Control structures)


=head1 Storing and retrieving questions and answers

* Reading questions from file
* Storing answers to file


=head1 Making a simple report

* Summing results
* Calculating average
* Presenting a nice report


=head1 Make the questionnaire into multiple choices


* Storing timestamps so we can report trends
*
* Writing a module
* 
* Changing files, and recogize the value of a source code control system (git?)
* Deployment (versioned modules, modules with author info)
* 

